### PR TITLE
Add example of querying data from a remote service.

### PR DESCRIPTION
**Pull request by steveworley**
- Includes the dotenv package.
- Add an example MarvelApi class to handle API requests.
- Add a comic schema file to inform the graphql server of the comic
type.
- Add a model to the comic schema that the API handler can use to format
the response from the API into an object that matches the grapql schema.
- Update the hero type to allow comics to be queried from the hero
class.

### CODE REVIEW

**Comment by steveworley** [comment]
@jenter I also changed the start command here to always include `dotenv/config` so we make sure to have access to the configuration in all modules. I didn't have any issues with ES6 syntax because I added the `babel-register` as well but it no longer uses babel-node to launch the application, if you have any issues let me know and we can figure it out!

**Comment by steveworley** [comment]
One last thing the `.env` file should just have a `KEY=VALUE` list. So it would look like:

```
API_PUBLIC_KEY=[marvel public key]
API_PRIVATE_KEY=[marvel private key]
```

**Comment by steveworley** [comment]
https://github.com/steveworley/javascript-ps-starter-graphql/pull/1

**Comment by jenter** [comment]
Awesome... !! merging now and reviewing

**Pull request merged**
